version: '3.9'
services:



      web:
            build: .
            command: sh -c "uvicorn app:app --reload --port=8000 --host=0.0.0.0"
            ports:
                  - 8000:8000
            depends_on:
                  - db
            networks:
                  - backend
      db:
            build: ./db/
            image: mysql:latest
            environment:
                  MYSQL_DATABASE: breast_cancer_db
                  MYSQL_ROOT_PASSWORD: Beytullah.123
                 
               
            networks:
                  - backend

   
      

networks:
            backend:
                  driver: bridge
                  name: backend